# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    """
    This is the set up class for the Song Sorter App Appication
    This class will create and place the objects on the Main Window,
    preparing the UI of the applicaiton.
    """
    def setupUi(self, MainWindow) -> None:
        """
        Set up the UI components for the main window.

        :param MainWindow: The main window instance
        :return: None
        """
        MainWindow
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(496, 454)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.song_sorter_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.song_sorter_label.setGeometry(QtCore.QRect(210, 20, 71, 21))
        self.song_sorter_label.setObjectName("song_sorter_label")
        self.song_sorter_description = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.song_sorter_description.setGeometry(QtCore.QRect(50, 50, 411, 111))
        self.song_sorter_description.setObjectName("song_sorter_description")
        self.add_song_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.add_song_label.setGeometry(QtCore.QRect(10, 170, 91, 16))
        self.add_song_label.setObjectName("add_song_label")
        self.titleadd_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.titleadd_label.setGeometry(QtCore.QRect(10, 230, 91, 16))
        self.titleadd_label.setObjectName("titleadd_label")
        self.artistadd_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.artistadd_label.setGeometry(QtCore.QRect(10, 210, 91, 16))
        self.artistadd_label.setObjectName("artistadd_label")
        self.add_artist_input = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.add_artist_input.setGeometry(QtCore.QRect(60, 210, 161, 21))
        self.add_artist_input.setObjectName("add_artist_input")
        self.add_title_input = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.add_title_input.setGeometry(QtCore.QRect(60, 230, 141, 21))
        self.add_title_input.setObjectName("add_title_input")
        self.rating_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.rating_label.setGeometry(QtCore.QRect(10, 250, 51, 16))
        self.rating_label.setObjectName("rating_label")
        self.user_description_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.user_description_label.setGeometry(QtCore.QRect(250, 210, 91, 16))
        self.user_description_label.setObjectName("user_description_label")
        self.user_description = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.user_description.setGeometry(QtCore.QRect(330, 200, 151, 81))
        self.user_description.setObjectName("user_description")
        self.rating = QtWidgets.QComboBox(parent=self.centralwidget)
        self.rating.setGeometry(QtCore.QRect(60, 250, 70, 26))
        self.rating.setObjectName("rating")
        self.rating.addItem("")
        self.rating.addItem("")
        self.rating.addItem("")
        self.rating.addItem("")
        self.rating.addItem("")
        self.rating.addItem("")
        self.rating.addItem("")
        self.rating.addItem("")
        self.rating.addItem("")
        self.rating.addItem("")
        self.remove_song_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.remove_song_label.setGeometry(QtCore.QRect(10, 310, 300, 16))
        self.remove_song_label.setObjectName("remove_song_label")
        self.remove_title_input = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.remove_title_input.setGeometry(QtCore.QRect(60, 360, 141, 21))
        self.remove_title_input.setObjectName("remove_title_input")
        self.artistremove_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.artistremove_label.setGeometry(QtCore.QRect(10, 340, 91, 16))
        self.artistremove_label.setObjectName("artistremove_label")
        self.remove_artist_input = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.remove_artist_input.setGeometry(QtCore.QRect(60, 340, 161, 21))
        self.remove_artist_input.setObjectName("remove_artist_input")
        self.titleremove_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.titleremove_label.setGeometry(QtCore.QRect(10, 360, 91, 16))
        self.titleremove_label.setObjectName("titleremove_label")
        self.save_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.save_button.setGeometry(QtCore.QRect(160, 270, 113, 32))
        self.save_button.setObjectName("save_button")
        self.remove_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.remove_button.setGeometry(QtCore.QRect(320, 330, 113, 32))
        self.remove_button.setObjectName("remove_button")
        self.message_to_user = QtWidgets.QLabel(parent=self.centralwidget)
        self.message_to_user.setGeometry(QtCore.QRect(290, 360, 181, 16))
        self.message_to_user.setObjectName("message_to_user")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 496, 33))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow)-> None:
        """
        Set the text and translations for all UI elements.

        :param MainWindow: The main window instance
        :return: None
        """

        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.song_sorter_label.setText(_translate("MainWindow", "Song Sorter App"))
        self.song_sorter_description.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Hello! This program will help you sort out your favorite songs. Enter the name of the artist, the song, and a ranking out of 10! You can also include an optional description of the song, like your favorite lyrics or something about it that you particularly like. Then the song will be added to the file songs.csv where you can access all of your favorite songs!</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.add_song_label.setText(_translate("MainWindow", "ADD A SONG:"))
        self.titleadd_label.setText(_translate("MainWindow", "Title:"))
        self.artistadd_label.setText(_translate("MainWindow", "Artist:"))
        self.rating_label.setText(_translate("MainWindow", "Rating:"))
        self.user_description_label.setText(_translate("MainWindow", "Description:"))
        self.rating.setItemText(0, _translate("MainWindow", "1"))
        self.rating.setItemText(1, _translate("MainWindow", "2"))
        self.rating.setItemText(2, _translate("MainWindow", "3"))
        self.rating.setItemText(3, _translate("MainWindow", "4"))
        self.rating.setItemText(4, _translate("MainWindow", "5"))
        self.rating.setItemText(5, _translate("MainWindow", "6"))
        self.rating.setItemText(6, _translate("MainWindow", "7"))
        self.rating.setItemText(7, _translate("MainWindow", "8"))
        self.rating.setItemText(8, _translate("MainWindow", "9"))
        self.rating.setItemText(9, _translate("MainWindow", "10"))
        self.remove_song_label.setText(_translate("MainWindow", "REMOVE A SONG:"))
        self.artistremove_label.setText(_translate("MainWindow", "Artist:"))
        self.titleremove_label.setText(_translate("MainWindow", "Title:"))
        self.save_button.setText(_translate("MainWindow", "SAVE"))
        self.remove_button.setText(_translate("MainWindow", "REMOVE"))
        self.message_to_user.setText(_translate("MainWindow", "Click button again to remove"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
